name: poktan_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  better_player: ^0.0.82
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  dropdown_search: ^3.0.1
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.0
  flutter_login: ^3.1.0
  flutter_svg: ^1.0.3
  format_indonesia: ^0.1.0
  get: 4.6.1
  get_storage: ^2.0.3
  getwidget: ^2.0.4
  http: ^0.13.4
  image_picker: ^0.8.5+3
  video_thumbnail: ^0.5.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
